### ISSUE TITLE
whisper method not available on private channels

### ISSUE THREAD

**Issue by splatEric** [alexxiyang/mock-echo#1]
I have a component which uses a private channel for communication. When I click on a button within the component, it is supposed to trigger a simple message into the private channel. However, at the moment, the whisper method does not appear to be available on the private channel that mock echo is providing:

`Error: Uncaught [TypeError: this.channel.whisper is not a function]`

Looking at the source, we have a `userWhisper` method, but no implementation of whisper. Is there a reason for this, is it an oversight, or am I misusing echo by trying to utilise this method?

**Comment by splatEric** [comment]
I've created a PR for this:

https://github.com/alexxiyang/mock-echo/pull/2

**Comment by CodePlato3721** [comment]
It's a good call! But I think changing `userWhisper` into `whisper` will be better than adding a new function. Would you help to do that? And update README.md as well?

**Comment by splatEric** [comment]
PR updated

**Comment by CodePlato3721** [comment]
Thanks

**Comment by splatEric** [comment]
@alexxiyang can you create a new release so that the PR is available from this repo rather than my fork?

**Comment by CodePlato3721** [comment]
Yep, check 1.1.0
